name: Welcome New Contributors
on:
  pull_request:
    types: [opened]  # Triggers when a PR is opened

jobs:
  welcome:
    runs-on: ubuntu-latest  # Uses a GitHub-hosted Linux machine
    steps:
      - name: Greet new contributor
        uses: actions/first-interaction@v1  # Official GitHub Action for greetings
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}  # Grants permission to comment
          pr-message: |  # Customizable message for PRs
            Hello @${{ github.actor }}! 🌟
            Thanks for your first contribution to this project! 
            A maintainer will review your PR shortly.
